### ISSUE TITLE
Variable does not update cardinality of variable

### ISSUE THREAD

**Issue by josecastro** [josecastro/AI#2]
The variable class can be initialised with values, but these currently do not update the cardinality field

**Comment by omobando** [comment]
I implemented a method to print the fields of the variable. It actually updates fine the field. I tried to initialize the variable with different domains and cardinality was set succesfully. I will commit the method to print the variable values.

**Comment by roycp** [comment]
upload the branch with the issue number as the name of the branch.
**create the branch**
  _git checkout -b < branch-name | AI-2 >_
**push the branch to github**
  _git push origin < branch-name | AI-2 >_

**Comment by omobando** [comment]
No usé branches. No soy experto en git. En eso se quedó?

**Comment by roycp** [comment]
Es para ver el codigo que hicistes :)
Te voy a describir los pasos para crear un branch y subirlo a github, te lo voy a poner en ingles. Los nombres como **NAMEOFTHEBRANCH** los cambias por algo más significativo como **AI-2** que es el  nombre del proyecto con numero del issue. Muy probablemente vas a poder hacer todo esto en un editor grafico, pero yo te lo pongo como se hace en consola. Si no puedes tranquilo seria algo extra.

**1. Create a branch**

> git checkout -b _NAMEOFTHEBRANCH_

**2. Work in your code**

> coding ... ... ...

**3. Commit your changes**

> git add .
> git commit -m _"descriptive message"_

**4. Upload your changes to github**

> git push origin _NAMEOFTHEBRANCH_

**5. Create a pull request of the branch**

> Github has a button in the homepage of the project for creating pull request.

In that way we can see your code :) :+1:

**Comment by omobando** [comment]
Thanks.

Anyway, in the commit detail you can see the code.

Regards

El 3 de marzo de 2015, 23:31, roycp notifications@github.com escribió:

> Es para ver el codigo que hicistes :)
> Te voy a describir los pasos para crear un branch y subirlo a github, te
> lo voy a poner en ingles. Los nombres como _NAMEOFTHEBRANCH_ los cambias
> por algo más significativo como _AI-2_ que es el nombre del proyecto con
> numero del issue. Muy probablemente vas a poder hacer todo esto en un
> editor grafico, pero yo te lo pongo como se hace en consola. Si no puedes
> tranquilo seria algo extra.
> 
> _1. Create a branch_
> 
> git checkout -b _NAMEOFTHEBRANCH_
> 
> _2. Work in your code_
> 
> coding ... ... ...
> 
> _3. Commit your changes_
> 
> git add .
> git commit -m _"descriptive message"_
> 
> _4. Upload your changes to github_
> 
> git push origin _NAMEOFTHEBRANCH_
> 
> _5. Create a pull request of the branch_
> 
> Github has a button in the homepage of the project for creating pull
> request.
> 
> In that way we can see your code :) [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/josecastro/AI/issues/2#issuecomment-77099688.

## 

-Oscar O.

**Comment by jnavas05** [comment]
Done
