### ISSUE TITLE
Factor map not initialised

### ISSUE THREAD

**Issue by josecastro** [josecastro/AI#3]
The Factor class contains a map with is currently not initialized, should be initialized with the indexes for the vector of values

**Comment by omobando** [comment]
You mean "Factor" class rigth ?

**Comment by josecastro** [comment]
Yep

**Comment by jnavas05** [comment]
I did implement Factor class constructor and run some tests.
Use of numpy arrays still to be done .

By the way, emacs, AWESOME (just have to memorize a couple shortcuts).

**Comment by jnavas05** [comment]
Now it is using numpy arrays.
Can anybody do some testing before closing this issue?

**Comment by jnavas05** [comment]
Done
